const { DB } = require("./config");
const { Pool } = require("pg");

const createBooks = `CREATE TABLE IF NOT EXISTS books (
    book_id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    book_name VARCHAR(100) NULL,
    summary VARCHAR(450) NULL,
    author VARCHAR(60) NULL,
    isbn  VARCHAR(60) NULL,
    publishing_year DATE NULL,
    genre VARCHAR(60) NULL,
    image VARCHAR(60) NULL,
    PRIMARY KEY (book_id));`;
const insertBooks = `
INSERT INTO books (book_name,summary,author,isbn,publishing_year,genre,image)
VALUES
  ('Sed','eu neque pellentesque massa lobortis ultrices. Vivamus rhoncus. Donec est.','Stuart Mckenzie','E5C55B5B-4B41-548E-8FB9-27486BDA05A1','Apr 10, 2021','Romance','094D4DC1-8561-06C8-A20C-D67918F5B921'),
  ('in','id magna et','Larissa Berger','45BB4E1A-3186-0811-D59B-CEA83CC45AA8','Oct 3, 2022','Dystopian','E98B125C-C9A9-7328-785D-E5A7E6251265'),
  ('feugiat','tincidunt congue turpis. In condimentum. Donec at arcu. Vestibulum ante','Octavia Franco','C6A28657-07D9-C712-20E2-A1D2666E42EC','Dec 26, 2022','Fantasy','CFBED0E6-996A-CDE4-1696-C4963AE61B98'),
  ('lectus','ut quam vel sapien imperdiet ornare. In faucibus. Morbi','Dara Shannon','BEE821A6-C169-1641-C0EF-4A4864C1322A','Apr 19, 2021','Sci-Fi','E17188C5-3245-43BC-39EA-82DC6EC15AC7'),
  ('vel','est, congue a, aliquet vel, vulputate eu, odio. Phasellus at augue id','Xena Strickland','E7073C91-74C3-B38C-E992-278C48992ADD','Apr 8, 2022','Sci-Fi','4BB8AE50-4821-324D-3825-153B29420155'),
  ('fermentum','ut, pellentesque eget, dictum placerat, augue. Sed molestie. Sed id risus quis','Dominic Battle','49725D94-B3AE-9419-30A6-3D44CBB71EFD','Jan 2, 2022','Thriller','6AE8B362-468C-ACC7-E67C-F3DF578F2E08'),
  ('magnis','at, libero.','Simon Webb','1EBAC622-AE6F-07E4-6A8E-61FDC146627C','Mar 14, 2022','Fantasy','492AC3EA-06D3-BC73-AEB5-E936F669C18C'),
  ('Vivamus','urna. Nunc quis arcu vel quam dignissim','Mufutau Yang','28581C8A-3397-7723-17D1-DC2DBD972439','Sep 28, 2022','Contemporary','22595CC1-891D-4334-22E7-4849668E4F3D'),
  ('velit','auctor. Mauris vel turpis. Aliquam adipiscing lobortis','Perry Waters','6B2A39E1-B46C-0663-59A3-133AF8689881','Sep 2, 2022','Romance','D87F6AF5-2576-5D35-4BE7-D9A4EBEBFE75'),
  ('tempus','a ultricies adipiscing, enim mi tempor lorem, eget','Kareem Howe','95787F28-87CD-F353-7A3C-B48A3F277E3C','Dec 16, 2022','Dystopian','B6480C4C-D915-EBB2-595B-043C3743636C'),
  ('In','fringilla mi','Salvador Kemp','D5819752-ED2C-70A2-86E5-5D0221CBBBAD','Apr 4, 2022','Sci-Fi','A8CDCD84-DE0B-F81F-6C4D-97ED4CC9BD73'),
  ('nunc','amet metus. Aliquam erat','Aimee Berry','54A27499-ADC2-A408-8A13-481A2A93D212','Jul 31, 2022','Thriller','599629BD-C756-B8D7-9704-2A9BD008C95D'),
  ('est','felis. Donec tempor, est ac','Noel Cantrell','7DBEE6B1-474F-B901-82A3-8EE0E9C98286','Oct 2, 2022','Dystopian','48664D91-CEC1-D6C9-635A-E3564F143612'),
  ('Quisque','vitae, sodales at,','Dieter Gilliam','0596EC15-BEA1-8A5D-264A-3AD7281C4C75','Dec 14, 2021','Romance','29CC0E1D-3C45-48D7-A1B6-4BD16BD2A14C'),
  ('amet,','dictum placerat, augue. Sed molestie. Sed id risus quis diam luctus','Zelenia Norman','B55814BD-D51B-2ADF-D4E3-AEB415EE3529','Jun 25, 2021','Thriller','9DE0583B-E1B1-22D6-F004-60EA4B52C621'),
  ('leo.','dictum mi, ac mattis velit justo nec ante. Maecenas mi','Jerome Cook','3D758D81-07AC-97F7-B2B7-979FC569BC7D','Feb 4, 2022','Contemporary','ADA29915-E411-E1C9-B65E-2606A68DBBBD'),
  ('Pellentesque','neque vitae semper egestas, urna justo faucibus lectus, a sollicitudin orci sem','Jin Keith','66CD7ABF-62C6-E53F-A27A-49E1525AB93A','Aug 20, 2022','Romance','7D6BB131-24B7-DAA8-F544-3C26BB13171D'),
  ('lectus.','lectus rutrum urna, nec luctus felis','Adena Valenzuela','9A8522A7-3B92-8A0A-B853-80374B332798','Apr 16, 2021','Sci-Fi','6961EEB1-A2EB-3CA5-9E0E-29266E932AEB'),
  ('justo.','Etiam bibendum fermentum metus. Aenean sed pede nec ante','Graiden Walsh','81CD0AA0-AE2D-745F-2310-3CEAE16D79CB','Feb 26, 2021','Dystopian','3D75A262-995F-AF92-4105-C4D8735DCAC2'),
  ('Curabitur','non, cursus non, egestas a, dui. Cras pellentesque. Sed dictum.','Dustin Mcconnell','97664C14-5583-132C-8974-112CB7ECA53E','Apr 10, 2021','Thriller','F6492F31-82C6-4E1A-44A3-75E0D8575DA5');
`;

const start = async () => {
  try {
    const pool = new Pool({
      user: DB.PGUSER,
      host: DB.PGHOST,
      database: DB.PGDATABASE,
      password: DB.PGPASSWORD,
      port: DB.PGPORT,
    });
    const start = Date.now();
    await pool.connect();
    await pool.query(createBooks);
    await pool.query(insertBooks);

    const duration = Date.now() - start;
    console.log({ msg: "executed query", duration });
    await pool.end();
  } catch (error) {
    console.log({ msg: "Database could not be setup", error });
    await pool.end();
  }
};

start();
